title: 欢迎来到余亚伦的个人主页！
description: 余亚伦的个人主页
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/avator_square.jpg"
email: yuyalun.allen@gmail.com
github_username:  yuyalun-allen

# Host settings
domain: yuyalun-allen.github.io       
url: https://yuyalun-allen.github.io 
# baseurl: /blogs # the subpath of your site, e.g. /blog

# Build settings
theme: jekyll-theme-satellite
plugins:
  - jekyll-feed

# # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                 #
#   Not recommended to touch the materials below  #
#                                                 #
#    Any changes may contribute to malfunction    #
#                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Build settings

# If you want to deploy Git Page, but choosing the second Installation method (described in README.md)
# rather than fork, then replace the below line with `remote_theme: byanko55/jekyll-theme-satellite`.
# Otherwise, DO NOT change it.
theme: jekyll-theme-satellite

exclude:
  - _posts
  - vendor

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
